title: Ojer
logo: /assets/img/ojer.jfif
description: sonamu@foxmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
    is_user_page: false
    is_project_page: false
    orderedlist: false
